import type { Product, StoreItem } from "./productCatalog"

export type MatchType = "Exact match" | "Closest match" | "Similar item"
export type RetailProduct = {
  productId: string; publisherId?: "gentlemans-gazette" | "story-and-rain"; mediaId?: string; hotspotId?: string; brand: string; productName: string
  category: string; color: string; pattern: string; price: string; currency: "USD" | "EUR" | "AUD" | "GBP"
  productImage: string; retailerUrl: string; matchType: MatchType; matchConfidence: number
  sourceUrl: string; similarProductIds: string[]; verificationStatus: "price-unverified-demo-fixture"
}
export type EditorialMedia = {
  id: string; publisherId?: "gentlemans-gazette" | "story-and-rain"; type: "image" | "video"; src: string; alt: string; sourceUrl?: string; editorial: boolean
  fashionReadable: boolean; hotspotIds: string[]; frameClassName?: string
  chipCorner?: "bottom-left" | "top-left"
}
export type HotspotRecord = { id: string; mediaId: string; productId: string; x: number; y: number; offsetX?: number; garment: string }

type Input = Omit<RetailProduct, "productId" | "sourceUrl" | "similarProductIds" | "matchType" | "matchConfidence" | "publisherId" | "verificationStatus"> & { confidence?: number; similar?: string[] }
function listing(productId: string, input: Input): RetailProduct {
  const { confidence, similar, ...rest } = input
  const publisherId = productId.startsWith("gg-") ? "gentlemans-gazette" : "story-and-rain"
  return { productId, publisherId, ...rest, sourceUrl:rest.retailerUrl, similarProductIds:similar ?? [], matchType:similar ? "Closest match" : "Similar item", matchConfidence:confidence ?? .7, verificationStatus:"price-unverified-demo-fixture" }
}

// Retailer names, prices and product photos are tied to the linked product listing.
// Photographed SKUs have not been independently verified, so primaries are closest matches.
export const RETAIL_PRODUCTS: Record<string, RetailProduct> = {
  "gg-jacket-zara": listing("gg-jacket-zara", { brand:"Zara", productName:"Houndstooth Double-Breasted Blazer", category:"Men's blazer", color:"Brown", pattern:"Houndstooth check", price:"$179", currency:"USD", productImage:"https://static.zara.net/assets/public/55bb/a63b/28f6446595c3/4436f7e900cc/04683667700-p/04683667700-p.jpg?f=auto&ts=1790065489713&w=560", retailerUrl:"https://www.zara.com/us/en/houndstooth-double-breasted-blazer-p04683667.html", confidence:.86, similar:["gg-jacket-reiss","gg-jacket-wessi"] }),
  "gg-jacket-reiss": listing("gg-jacket-reiss", { brand:"Reiss", productName:"Penso Wool-Blend Check Double-Breasted Suit Blazer", category:"Men's blazer", color:"Chocolate brown", pattern:"Prince of Wales check", price:"$347", currency:"USD", productImage:"https://cdn.platform.next/common/items/default/default/itemimages/3_4Ratio/product/lge/V79129s.jpg?im=Resize%2Cwidth%3D750", retailerUrl:"https://www.reiss.com/us/en/style/sv076152/v79129" }),
  "gg-jacket-wessi": listing("gg-jacket-wessi", { brand:"Wessi", productName:"Checked Double Breasted Brown Men Blazer", category:"Men's blazer", color:"Brown", pattern:"Check", price:"$199", currency:"USD", productImage:"https://www.wessi.com/cdn/shop/files/output_5dc0e192-bb55-48d3-8cf6-ea12505be008.png?v=1765993860&width=1080", retailerUrl:"https://www.wessi.com/products/checked-double-breasted-brown-men-blazer-wessi" }),
  "gg-shirt-twill": listing("gg-shirt-twill", { brand:"Charles Tyrwhitt", productName:"Non-Iron Twill Shirt - Light Blue", category:"Men's dress shirt", color:"Light blue", pattern:"Solid twill", price:"$129", currency:"USD", productImage:"https://www.charlestyrwhitt.com/dw/image/v2/AAWJ_PRD/on/demandware.static/-/Sites-ctshirts-master/default/dwa9980d27/hi-res/FON2637CEB_MODEL_FULL.jpg?sh=1200&sw=960", retailerUrl:"https://www.charlestyrwhitt.com/us/non-iron-twill-shirt---light-blue/FON2638CEB14H2S.html", confidence:.8, similar:["gg-shirt-oxford","gg-shirt-greenwich","gg-shirt-sky"] }),
  "gg-shirt-oxford": listing("gg-shirt-oxford", { brand:"Charles Tyrwhitt", productName:"Non-Iron Stretch Oxford Shirt - Light Blue", category:"Men's dress shirt", color:"Light blue", pattern:"Solid Oxford", price:"$139", currency:"USD", productImage:"https://www.charlestyrwhitt.com/dw/image/v2/AAWJ_PRD/on/demandware.static/-/Sites-ctshirts-master/default/dwd4586c8d/SCS/SCS0068LBU/SCS0068LBU_MODEL_FULL_02.jpg?sh=1200&sw=960", retailerUrl:"https://www.charlestyrwhitt.com/us/non-iron-stretch-oxford-shirt---light-blue/SCS0065LBU175S.html" }),
  "gg-shirt-greenwich": listing("gg-shirt-greenwich", { brand:"Charles Tyrwhitt", productName:"Non-Iron Stretch Greenwich Weave Shirt - Light Blue", category:"Men's dress shirt", color:"Light blue", pattern:"Solid textured weave", price:"$139", currency:"USD", productImage:"https://www.charlestyrwhitt.com/dw/image/v2/AAWJ_PRD/on/demandware.static/-/Sites-ctshirts-master/default/dw6bb35264/FOA/FOA0012LBU/FOA0012LBU_MODEL_FULL_02.jpg?sh=1200&sw=960", retailerUrl:"https://www.charlestyrwhitt.com/us/non-iron-stretch-greenwich-weave-shirt---light-blue/FOA0015LBU14H2S.html" }),
  "gg-shirt-sky": listing("gg-shirt-sky", { brand:"Charles Tyrwhitt", productName:"Non-Iron Twill Shirt - Sky Blue", category:"Men's dress shirt", color:"Sky blue", pattern:"Solid twill", price:"$129", currency:"USD", productImage:"https://www.charlestyrwhitt.com/dw/image/v2/AAWJ_PRD/on/demandware.static/-/Sites-ctshirts-master/default/dw793222ce/SCB/SCB0005SKY/SCB0005SKY_MODEL_TIE_07.jpg?sh=1200&sw=960", retailerUrl:"https://www.charlestyrwhitt.com/us/non-iron-twill-shirt---sky-blue/SCB0005SKY.html" }),
  "sr-blazer-gelso": listing("sr-blazer-gelso", { brand:"The Frankie Shop", productName:"Gelso Oversized Blazer - Dark Grey Melange", category:"Women's blazer", color:"Dark grey melange", pattern:"Solid", price:"$425", currency:"USD", productImage:"https://thefrankieshop.com/cdn/shop/files/image00089_8d82ef79-8cd8-4d3b-a65f-e2b71d224444.jpg?v=1706875814&width=1200", retailerUrl:"https://thefrankieshop.com/products/gelso-oversized-blazer-dark-grey-melange", confidence:.82, similar:["sr-blazer-bea","sr-blazer-dee","sr-blazer-pia"] }),
  "sr-blazer-bea": listing("sr-blazer-bea", { brand:"The Frankie Shop", productName:"Bea Blazer - Charcoal", category:"Women's blazer", color:"Charcoal", pattern:"Solid", price:"$385", currency:"USD", productImage:"https://thefrankieshop.com/cdn/shop/products/BeaBlazer-Charcoal-BeaSuitPants-Charcoal-savanah-29juin43481_1.jpg?v=1665436303&width=1200", retailerUrl:"https://thefrankieshop.com/products/bea-blazer-charcoal" }),
  "sr-blazer-dee": listing("sr-blazer-dee", { brand:"The Frankie Shop", productName:"Dee Maxi Oversized Blazer - Charcoal", category:"Women's blazer", color:"Charcoal", pattern:"Solid", price:"€379", currency:"EUR", productImage:"https://eu.thefrankieshop.com/cdn/shop/products/Dee-Maxi-Oversized-Blazer-Charcoal-l8341.jpg?v=1661204003&width=1200", retailerUrl:"https://eu.thefrankieshop.com/products/dee-maxi-oversized-blazer-charcoal" }),
  "sr-blazer-pia": listing("sr-blazer-pia", { brand:"The Frankie Shop", productName:"Pia Boxy Blazer - Grey", category:"Women's blazer", color:"Grey", pattern:"Solid", price:"$263", currency:"USD", productImage:"https://thefrankieshop.com/cdn/shop/files/PIA-BOXY-BLAZER-GREY-LETA-202459513.jpg?v=1708080896&width=1200", retailerUrl:"https://thefrankieshop.com/products/pia-boxy-blazer-grey" }),
  "sr-vest-gelso": listing("sr-vest-gelso", { brand:"The Frankie Shop", productName:"Gelso Waistcoat - Dark Grey Melange", category:"Women's waistcoat", color:"Dark grey melange", pattern:"Solid", price:"$235", currency:"USD", productImage:"https://thefrankieshop.com/cdn/shop/files/gelso-waistcoat-dark-grey-melange-vest-the-frankie-shop-666209_de4c57b2-d910-4bea-bd20-a97ec5f3ec90.jpg?v=1749896499&width=1200", retailerUrl:"https://thefrankieshop.com/products/gelso-waistcoat-dark-grey-melange", confidence:.82, similar:["sr-vest-ivey","sr-vest-bettas","sr-vest-holborn"] }),
  "sr-vest-ivey": listing("sr-vest-ivey", { brand:"The Frankie Shop", productName:"Ivey Vest - Grey Melange", category:"Women's waistcoat", color:"Grey melange", pattern:"Light plaid", price:"$48", currency:"USD", productImage:"https://thefrankieshop.com/cdn/shop/files/IVEY-VEST-GREY-MELANGE-JULIA-22135.jpg?v=1747995821&width=1200", retailerUrl:"https://thefrankieshop.com/products/ivey-vest-grey-melange" }),
  "sr-vest-bettas": listing("sr-vest-bettas", { brand:"By Malene Birger", productName:"Bettas Waistcoat - Grey Melange", category:"Women's waistcoat", color:"Grey melange", pattern:"Solid", price:"€104", currency:"EUR", productImage:"https://eu.thefrankieshop.com/cdn/shop/products/BY-MALENE-BIRGER-BETTAS-WAISTCOAT-GREY-MELANGE-TARA-47046.jpg?v=1710339201&width=1200", retailerUrl:"https://eu.thefrankieshop.com/products/by-malene-birger-bettas-waistcoat-grey-melange" }),
  "sr-vest-holborn": listing("sr-vest-holborn", { brand:"The Frankie Shop", productName:"Holborn Double-Breasted Vest - Grey Melange", category:"Women's waistcoat", color:"Grey melange", pattern:"Solid", price:"€235", currency:"EUR", productImage:"https://eu.thefrankieshop.com/cdn/shop/files/HOLBORN-DOUBLE-BREASTED-VEST-GREY-MELANGE-MAME-0954-W.jpg?v=1780906418&width=1200", retailerUrl:"https://eu.thefrankieshop.com/products/holborn-double-breasted-vest-grey-melange" }),
  "gg-overcoat-daks": listing("gg-overcoat-daks", { brand:"DAKS / Chrysalis", productName:"Kensington Windowpane Overcoat - Brown", category:"Men's overcoat", color:"Brown", pattern:"Windowpane check", price:"£995", currency:"GBP", productImage:"https://daks.com/cdn/shop/files/MW04FM2Q6239_F_1200x.jpg?v=1758538226", retailerUrl:"https://daks.com/products/kensington-coat-daks-london" }),
  "gg-evening-velvet": listing("gg-evening-velvet", { brand:"KCT Menswear", productName:"Burgundy Velvet Dinner Jacket", category:"Men's dinner jacket", color:"Burgundy", pattern:"Solid velvet", price:"$229.99", currency:"USD", productImage:"https://cdn.shopify.com/s/files/1/0002/9360/1332/products/burgundy-jacquard-shiny-slim-fit-prom-blazer-2-prom-blazer-wessi-201656-51-B_1800x1800_222dacad-d870-4666-89b8-408203b88e1d.jpg?v=1663898227&width=1200", retailerUrl:"https://kctmenswear.com/product/burgundy-velvet-blazer" }),
  "gg-suit-navy": listing("gg-suit-navy", { brand:"Charles Tyrwhitt", productName:"Navy Stripe Suit Jacket", category:"Men's suit jacket", color:"Navy", pattern:"Subtle stripe", price:"Check retailer", currency:"USD", productImage:"https://www.charlestyrwhitt.com/on/demandware.static/-/Sites-ctshirts-master/default/dwae330768/hi-res/SUB0605NAV_JACKET_FRONT.jpg", retailerUrl:"https://www.charlestyrwhitt.com/us/suit-jacket---navy-stripe/SUB0605NAV.html" }),
  "gg-sunglasses-wayfarer": listing("gg-sunglasses-wayfarer", { brand:"Ray-Ban", productName:"Original Wayfarer Classic", category:"Sunglasses", color:"Black", pattern:"Solid", price:"$191", currency:"USD", productImage:"https://images2.ray-ban.com//prod-onecp-record-files/pieyewear/aa3935f3-184a-4e17-a880-b35d00c65c8a/0RB2140__901__P21__shad__qt.png?impolicy=RB_Product_clone&width=1440&bgc=%23f2f2f2", retailerUrl:"https://www.ray-ban.com/usa/sunglasses/RB2140%20UNISEX%20062-original%20wayfarer%20classic-black/805289126577" }),
  "gg-pitti-coat": listing("gg-pitti-coat", { brand:"DAKS / Chrysalis", productName:"Kensington Windowpane Overcoat - Brown", category:"Men's overcoat", color:"Brown", pattern:"Windowpane check", price:"£995", currency:"GBP", productImage:"https://daks.com/cdn/shop/files/MW04FM2Q6239_F_1200x.jpg?v=1758538226", retailerUrl:"https://daks.com/products/kensington-coat-daks-london" }),
  "sr-red-lace": listing("sr-red-lace", { brand:"Bebe / Macy's", productName:"Dark Red Lace Bodice Pencil Dress", category:"Women's lace dress", color:"Dark red", pattern:"Lace bodice", price:"$149", currency:"USD", productImage:"https://slimages.macysassets.com/is/image/MCY/products/0/optimized/27331370_fpx.tif?wid=800", retailerUrl:"https://www.macys.com/shop/product/bebe-womens-lace-bodice-pencil-dress?ID=18054816" }),
  "sr-white-shirt": listing("sr-white-shirt", { brand:"UNIQLO", productName:"Cotton Oversized Shirt", category:"Women's shirt", color:"White", pattern:"Solid", price:"Check retailer", currency:"USD", productImage:"https://image.uniqlo.com/UQ/ST3/us/imagesgoods/483880/item/usgoods_00_483880_3x4.jpg?width=600", retailerUrl:"https://www.uniqlo.com/us/en/products/E483880-000/00" }),
  "sr-denim-jacket": listing("sr-denim-jacket", { brand:"Levi's", productName:"Original Trucker Jacket", category:"Women's denim jacket", color:"Blue denim", pattern:"Solid denim", price:"$110", currency:"USD", productImage:"https://lsco.scene7.com/is/image/lsco/299450036-front-pdp", retailerUrl:"https://www.levi.com/US/en_US/clothing/women/outerwear/jean-jackets/original-trucker-jacket/p/299450036" }),
  "sr-smiley-crewneck": listing("sr-smiley-crewneck", { brand:"Smiley x Sesame Street", productName:"Smile Through It Waffle Crewneck", category:"Women's sweatshirt", color:"Yellow", pattern:"Graphic", price:"£70", currency:"GBP", productImage:"https://smiley.com/cdn/shop/files/Y1.webp?height=1280&v=1755762951&width=1024", retailerUrl:"https://smiley.com/products/sesame-street-smile-through-it-waffle-crewneck-yellow" }),
  "sr-patterned-dress": listing("sr-patterned-dress", { brand:"NAIA", productName:"Lily Black and White Patterned Dress", category:"Women's dress", color:"Black and white", pattern:"Floral print", price:"Check retailer", currency:"USD", productImage:"https://us.naiaofficial.com/cdn/shop/files/LILY-DRESS-BLACK-WHITE-FLOWER-PATTERNED.jpg?v=1710348258&width=1200", retailerUrl:"https://us.naiaofficial.com/products/lily-dress-black-white-flower-patterned" }),
}

export const HOTSPOTS: Record<string, HotspotRecord> = {
  "gg-jacket": { id:"gg-jacket", mediaId:"gg-group-portrait", productId:"gg-jacket-zara", x:43, y:66, garment:"brown checked double-breasted jacket" },
  "gg-shirt": { id:"gg-shirt", mediaId:"gg-group-portrait", productId:"gg-shirt-twill", x:46, y:44, garment:"pale blue dress shirt" },
  "sr-blazer": { id:"sr-blazer", mediaId:"sr-lily-suit", productId:"sr-blazer-gelso", x:53, y:46, garment:"oversized grey blazer" },
  "sr-waistcoat": { id:"sr-waistcoat", mediaId:"sr-lily-suit", productId:"sr-vest-gelso", x:63, y:42, garment:"grey tailored waistcoat" },
  "gg-overcoat": { id:"gg-overcoat", mediaId:"gg-overcoat", productId:"gg-overcoat-daks", x:22, y:48, garment:"green windowpane overcoat" },
  "gg-overcoat-suit": { id:"gg-overcoat-suit", mediaId:"gg-overcoat", productId:"gg-suit-navy", x:49, y:39, garment:"navy suit jacket beneath the overcoat" },
  "gg-evening": { id:"gg-evening", mediaId:"gg-eveningwear", productId:"gg-evening-velvet", x:50, y:52, garment:"burgundy velvet dinner jacket" },
  "gg-eyewear": { id:"gg-eyewear", mediaId:"gg-sunglasses", productId:"gg-sunglasses-wayfarer", x:49, y:44, garment:"black sunglasses" },
  "gg-pitti": { id:"gg-pitti", mediaId:"gg-pitti-streetstyle", productId:"gg-pitti-coat", x:19, y:50, garment:"brown tailored coat" },
  "sr-cover-dress": { id:"sr-cover-dress", mediaId:"sr-cover-story", productId:"sr-red-lace", x:48, y:54, garment:"red lace dress" },
  "sr-hayes-dress": { id:"sr-hayes-dress", mediaId:"sr-hayes-card", productId:"sr-red-lace", x:49, y:57, garment:"red lace dress" },
  "sr-white-shirt": { id:"sr-white-shirt", mediaId:"sr-white-shirt", productId:"sr-white-shirt", x:52, y:48, garment:"oversized white shirt" },
  "sr-screened-denim": { id:"sr-screened-denim", mediaId:"sr-screened-arielle", productId:"sr-denim-jacket", x:49, y:65, garment:"blue denim jacket" },
  "sr-beauty-top": { id:"sr-beauty-top", mediaId:"sr-treat-body", productId:"sr-smiley-crewneck", x:53, y:56, garment:"yellow smiley graphic top" },
  "sr-jenny-dress": { id:"sr-jenny-dress", mediaId:"sr-jenny-slate-video-still", productId:"sr-patterned-dress", x:47, y:57, garment:"black and white patterned dress" },
}
export const PUBLISHER_MEDIA: Record<string, EditorialMedia> = {
  "gg-group-portrait": { id:"gg-group-portrait", publisherId:"gentlemans-gazette", type:"image", src:"/assets/gg-editorial-banner.jpg", sourceUrl:"https://www.gentlemansgazette.com/", alt:"Three Gentleman's Gazette contributors in tailoring; the central man wears a brown checked double-breasted jacket and pale blue shirt", editorial:true, fashionReadable:true, hotspotIds:["gg-jacket","gg-shirt"], frameClassName:"gazette-media-frame", chipCorner:"top-left" },
  "sr-lily-suit": { id:"sr-lily-suit", publisherId:"story-and-rain", type:"image", src:"/assets/sr-well-suited.jpg", sourceUrl:"https://storyandrain.com/article/well-suited", alt:"Lily Rabe in an oversized grey three-piece suit photographed for Story + Rain's Well Suited editorial", editorial:true, fashionReadable:true, hotspotIds:["sr-blazer","sr-waistcoat"], frameClassName:"storyrain-media-frame", chipCorner:"top-left" },
  "gg-overcoat": { id:"gg-overcoat", publisherId:"gentlemans-gazette", type:"image", src:"https://www.gentlemansgazette.com/wp-content/uploads/2021/10/articlesandvideos-e1647985755465.jpg", sourceUrl:"https://www.gentlemansgazette.com/archive/", alt:"Gentleman wearing a green windowpane overcoat over a navy suit", editorial:true, fashionReadable:true, hotspotIds:["gg-overcoat","gg-overcoat-suit"], frameClassName:"gazette-media-frame", chipCorner:"top-left" },
  "gg-eveningwear": { id:"gg-eveningwear", publisherId:"gentlemans-gazette", type:"image", src:"https://www.gentlemansgazette.com/wp-content/uploads/2021/10/morningwear-detail-e1647985794625.jpg", sourceUrl:"https://www.gentlemansgazette.com/archive/", alt:"Man in burgundy velvet evening jacket against a green wall", editorial:true, fashionReadable:true, hotspotIds:["gg-evening"], frameClassName:"gazette-media-frame", chipCorner:"top-left" },
  "gg-sunglasses": { id:"gg-sunglasses", publisherId:"gentlemans-gazette", type:"image", src:"https://www.gentlemansgazette.com/wp-content/uploads/2022/02/Raphael-Sunglasses-1-588x588.jpg", sourceUrl:"https://www.gentlemansgazette.com/archive/", alt:"Gentleman's Gazette founder wearing black sunglasses and leather gloves", editorial:true, fashionReadable:true, hotspotIds:["gg-eyewear"], frameClassName:"gazette-media-frame", chipCorner:"top-left" },
  "gg-pitti-streetstyle": { id:"gg-pitti-streetstyle", publisherId:"gentlemans-gazette", type:"image", src:"https://www.gentlemansgazette.com/wp-content/uploads/2022/02/Gentlemen-walking-at-Pitti-Uomo-1.jpg", sourceUrl:"https://www.gentlemansgazette.com/archive/", alt:"Gentlemen in tailored coats walking at Pitti Uomo", editorial:true, fashionReadable:true, hotspotIds:["gg-pitti"], frameClassName:"gazette-media-frame", chipCorner:"top-left" },
  "sr-cover-story": { id:"sr-cover-story", publisherId:"story-and-rain", type:"image", src:"https://images.ctfassets.net/mk0gyd3cqdg6/YxiwoWWhlOtzXkbO9K5HL/a48280cd3f93b1e291967c3db6493359/_DSC0639_1_.jpg?w=1680&h=945&fit=fill&fm=jpg", sourceUrl:"https://storyandrain.com/article/hayes-warner-tv-film-music-cover-uncovered-be-warned", alt:"Story + Rain cover photograph of a model in a red lace look against a dark blue background", editorial:true, fashionReadable:true, hotspotIds:["sr-cover-dress"], frameClassName:"storyrain-media-frame", chipCorner:"top-left" },
  "sr-hayes-card": { id:"sr-hayes-card", publisherId:"story-and-rain", type:"image", src:"https://images.ctfassets.net/mk0gyd3cqdg6/YxiwoWWhlOtzXkbO9K5HL/a48280cd3f93b1e291967c3db6493359/_DSC0639_1_.jpg?w=1200&h=2006&fit=fill&fm=jpg", sourceUrl:"https://storyandrain.com/article/hayes-warner-tv-film-music-cover-uncovered-be-warned", alt:"Story + Rain editorial portrait in a red lace look", editorial:true, fashionReadable:true, hotspotIds:["sr-hayes-dress"], frameClassName:"storyrain-media-frame", chipCorner:"top-left" },
  "sr-white-shirt": { id:"sr-white-shirt", publisherId:"story-and-rain", type:"image", src:"https://images.ctfassets.net/mk0gyd3cqdg6/4Il02OscYts3XquZnlDWK7/cb96873f6f55bfd48dfeee706b69255c/BALANCIAGA_2026.avif", sourceUrl:"https://storyandrain.com/article/shopping-style-shop-the-right-white-shirt", alt:"Editorial photograph of an oversized white shirt and black trousers on a runway", editorial:true, fashionReadable:true, hotspotIds:["sr-white-shirt"], frameClassName:"storyrain-media-frame", chipCorner:"top-left" },
  "sr-screened-arielle": { id:"sr-screened-arielle", publisherId:"story-and-rain", type:"image", src:"https://images.ctfassets.net/mk0gyd3cqdg6/JU46b5dL3AI136sPXI8NT/951329ba306166f6da7e7543bc11bac9/ARIELLE_KEBBEL___STORY___RAIN_1.jpg?w=700&h=700&fit=fill&fm=jpg", sourceUrl:"https://storyandrain.com/article/tv-film-screened-arielle-kebbel", alt:"Arielle Kebbel wearing a denim jacket in a Story + Rain Screened portrait", editorial:true, fashionReadable:true, hotspotIds:["sr-screened-denim"], frameClassName:"storyrain-media-frame", chipCorner:"top-left" },
  "sr-treat-body": { id:"sr-treat-body", publisherId:"story-and-rain", type:"image", src:"https://images.ctfassets.net/mk0gyd3cqdg6/5EkeFNKKw72U9kHcuTaDW6/e27050908f6a5ec3ef5862ce36d9d3df/HANNAH_CORBIN___STORY___RAIN_12.1.25_5.jpg?w=700&h=700&fit=fill&fm=jpg", sourceUrl:"https://storyandrain.com/article/treat-your-body-by-hannah-corbin-week-of-december-1-2025", alt:"Hannah Corbin wearing a yellow smiley graphic top in a Story + Rain wellness feature", editorial:true, fashionReadable:true, hotspotIds:["sr-beauty-top"], frameClassName:"storyrain-media-frame", chipCorner:"top-left" },
  "sr-jenny-slate-video-still": { id:"sr-jenny-slate-video-still", publisherId:"story-and-rain", type:"image", src:"https://downloads.ctfassets.net/mk0gyd3cqdg6/4QnO6Yi7sLOd821d69ZO1v/00eaefa286fccba7d579b438421434ad/JENNY_SLATE___STORY___RAIN_FEAT_5.jpg?w=800&h=450&fit=fill&fm=jpg&fl=progressive", sourceUrl:"https://storyandrain.com/article/jenny-slate-video-behind-scenes-bts-april-2025-cover", alt:"Jenny Slate wearing a black and white patterned dress in a Story + Rain video still", editorial:true, fashionReadable:true, hotspotIds:["sr-jenny-dress"], frameClassName:"storyrain-media-frame", chipCorner:"top-left" },
}
function asStoreItem(record: RetailProduct, id: number): StoreItem {
  return { ...record, price:"Check retailer", priceNote:"Demo catalog match. Price, size and availability have not been verified; check the retailer listing.", id, name:record.productName, image:record.productImage, url:record.retailerUrl }
}
export const CATALOG_ADAPTER = { kind:"local-fixtures" as const, endpoint:null, checkedAt:"2026-10-05", note:"No product-recognition API or credentials are configured in this checkout. These hand-authored fixtures are visual alternatives, not recognition results." }
const productCache: Record<string, Product[]> = {}
export function productsForMedia(mediaId: string): Product[] {
  if (productCache[mediaId]) return productCache[mediaId]
  const media = PUBLISHER_MEDIA[mediaId]
  if (!media) return []
  productCache[mediaId] = media.hotspotIds.map((hotspotId, index) => {
    const hotspot = HOTSPOTS[hotspotId], record = RETAIL_PRODUCTS[hotspot.productId]
    return { ...asStoreItem({ ...record, mediaId, hotspotId }, 1000 + index), x:hotspot.x, y:hotspot.y, offsetX:hotspot.offsetX, similar:record.similarProductIds.map((id, similarIndex) => asStoreItem(RETAIL_PRODUCTS[id], 2000 + index * 100 + similarIndex)) }
  })
  return productCache[mediaId]
}
export function isEligibleEditorialMedia(media: Pick<EditorialMedia, "type" | "editorial" | "alt"> & { fashionReadable?: boolean; products?: Product[] }, width: number, height: number) {
  return media.editorial && media.fashionReadable !== false && Boolean(media.alt.trim()) && (media.type === "image" || media.type === "video") && (media.products?.length ?? 1) > 0 && width >= 240 && height >= 180
}
